# Dockerfile for static assets of website. It's insane how much is *actually*
# happening here, even given the relative simplicity of this code.
FROM nginx:mainline-alpine
COPY . /usr/share/nginx/html
EXPOSE 80
